services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  mehmetimga/quarto-python-project:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/mehmet/quarto-python-project
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64